const groups = {
  vowels: { label: '母音', sub: '基本母音', color: 'mint', cards: [['ㅏ','a','a'],['ㅓ','eo','ŏ'],['ㅗ','o','o'],['ㅜ','u','u'],['ㅡ','eu','ŭ'],['ㅣ','i','i'],['ㅐ','ae','ae'],['ㅔ','e','e']] },
  w: { label: 'W 系列', sub: '複合母音', color: 'yellow', cards: [['ㅘ','wa','wa'],['ㅙ','wae','wae'],['ㅚ','oe','we'],['ㅝ','wo','wŏ'],['ㅞ','we','we'],['ㅟ','wi','wi'],['ㅢ','ui','ŭi']] },
  y: { label: 'Y 系列', sub: '滑音母音', color: 'blue', cards: [['ㅑ','ya','ya'],['ㅕ','yeo','yŏ'],['ㅛ','yo','yo'],['ㅠ','yu','yu'],['ㅒ','yae','yae'],['ㅖ','ye','ye']] },
  consonants: { label: '子音', sub: '基本子音', color: 'orange', cards: [['ㅂ','b / p','b'],['ㅍ','p','p'],['ㅁ','m','m'],['ㄷ','d / t','d'],['ㅌ','t','t'],['ㄴ','n','n'],['ㄹ','r / l','r'],['ㄱ','g / k','g'],['ㅋ','k','k'],['ㅇ','ng / —','ng'],['ㅎ','h','h'],['ㅈ','j','j'],['ㅊ','ch','ch'],['ㅅ','s','s']] },
  tense: { label: '硬音', sub: '緊音子音', color: 'tense', cards: [['ㄲ','kk','ㄲ'],['ㄸ','tt','ㄸ'],['ㅃ','pp','ㅃ'],['ㅆ','ss','ㅆ'],['ㅉ','jj','ㅉ']] },
  words: { label: '單字', sub: 'Korean words', color: 'word', cards: [['한국','hanguk','韓國'],['서울','seoul','Seoul／首爾'],['부산','busan','釜山／Busan'],['강남','gangnam','江南／Gangnam'],['강남스타일','gangnam seutail','江南 Style'],['인천','incheon','仁川／Incheon'],['삼성','samseong','三星／Samsung'],['현대','hyeondae','現代／Hyundai'],['나이키','naiki','Nike'],['스타벅스','seutabeokseu','Starbucks／星巴克'],['블랙핑크','beullaekpingkeu','BLACKPINK'],['뉴진스','nyujinseu','NewJeans'],['커피','keopi','coffee'],['콜라','kolla','cola'],['카페','kape','café'],['메뉴','menyu','menu'],['호텔','hotel','hotel'],['택시','taeksi','taxi'],['버스','beoseu','bus'],['태권도','taekwondo','跆拳道'],['병원','byeongwon','病院'],['은행','eunhaeng','銀行'],['입구','ipgu','入口'],['출구','chulgu','出口'],['지하철','jihacheol','地下鐵'],['공항','gonghang','空港'],['화장실','hwajangsil','化粧室'],['도서관','doseogwan','圖書館'],['박물관','bangmulgwan','博物館'],['무료','muryo','無料／免費']] }
};
const AUDIO_ROOT = 'audio/consonants/';
const AUDIO_FILES = {'ㄱ':'ㄱ_g.mp3','ㄲ':'ㄲ_gg.mp3','ㄴ':'ㄴ_n.mp3','ㄷ':'ㄷ_d.mp3','ㄸ':'ㄸ_dd.mp3','ㄹ':'ㄹ_l.mp3','ㅁ':'ㅁ_m.mp3','ㅂ':'ㅂ_b.mp3','ㅃ':'ㅃ_bb.mp3','ㅅ':'ㅅ_s.mp3','ㅆ':'ㅆ_ss.mp3','ㅈ':'ㅈ_j.mp3','ㅉ':'ㅉ_jj.mp3','ㅊ':'ㅊ_ch.mp3','ㅋ':'ㅋ_k.mp3','ㅌ':'ㅌ_t.mp3','ㅍ':'ㅍ_p.mp3','ㅎ':'ㅎ_h.mp3'};
let current = 'vowels'; let seen = new Set(); let soundOn = true; let activeAudio = null; let playingKey = null; let sequenceTimer = null;
const tabs = document.querySelector('#tabs'), cards = document.querySelector('#cards'), count = document.querySelector('#cardCount'), progress = document.querySelector('#progressNumber');
function stopCurrentAudio(){ if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null;} if('speechSynthesis' in window) speechSynthesis.cancel(); playingKey=null; }
function setPlayAllButton(playing){ const button=document.querySelector('#playAll'); button.innerHTML=playing?'<span>■</span> 停止播放':'<span>▶</span> 播放這一組'; }
function stopCurrentAudio(updateButton=true){ if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null;} if('speechSynthesis' in window) speechSynthesis.cancel(); playingKey=null; if(updateButton)setPlayAllButton(false); }
function speak(symbol,key='single'){ if(!soundOn) return; if(key!=='sequence' && sequenceTimer){clearTimeout(sequenceTimer);sequenceTimer=null;} stopCurrentAudio(false); playingKey=key; setPlayAllButton(key==='sequence'); if(AUDIO_FILES[symbol]){ activeAudio=new Audio(encodeURI(AUDIO_ROOT+AUDIO_FILES[symbol])); activeAudio.onended=()=>{activeAudio=null;playingKey=null;setPlayAllButton(false)}; activeAudio.play().catch(()=>{playingKey=null;setPlayAllButton(false)}); return; } if(!('speechSynthesis' in window)) return; const u = new SpeechSynthesisUtterance(symbol); u.lang='ko-KR'; u.rate=.72; u.onend=()=>{playingKey=null;setPlayAllButton(false)}; speechSynthesis.speak(u); }
function renderTabs(){ tabs.innerHTML = Object.entries(groups).map(([key,g])=>`<button class="tab ${key===current?'active':''}" data-group="${key}">${g.label}<span class="tab-count">${g.cards.length}</span></button>`).join(''); tabs.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.group;renderTabs();renderCards();})); }
function renderCards(){ const g=groups[current]; const isWords=current==='words'; count.textContent=`${g.cards.length} cards`; document.querySelector('#sectionTitle').textContent=isWords?'選一個單字，聽見它的聲音。':'選一組，開始辨認聲音。'; cards.innerHTML=g.cards.map((c,i)=>`<article class="card ${isWords?'word-card ':''}${seen.has(current+'-'+i)?'seen':''}" tabindex="0" data-index="${i}" aria-label="${c[0]}，羅馬拼音 ${c[1]}，點擊翻面並播放發音"><div class="card-inner"><div class="card-face card-front"><span class="card-index">0${i+1}</span><span class="card-symbol">${c[0]}</span></div><div class="card-face card-back"><span class="card-symbol">${c[0]}</span><span class="roman">${c[1]}</span><span class="pronounce">${c[2]}</span><button class="play-card" aria-label="播放或停止 ${c[0]} 的發音">▶</button></div></div></article>`).join(''); cards.querySelectorAll('.card').forEach(card=>{ const i=Number(card.dataset.index); const key=current+'-'+i; const flip=()=>{card.classList.toggle('flipped');seen.add(key);updateProgress();if(playingKey===key)stopCurrentAudio();else speak(g.cards[i][0],key)}; card.addEventListener('click',e=>{if(e.target.closest('.play-card')){e.stopPropagation();if(playingKey===key)stopCurrentAudio();else speak(g.cards[i][0],key);return}flip()}); card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}}); }); }
function updateProgress(){progress.textContent=seen.size;}
document.querySelector('#soundToggle').addEventListener('click',e=>{soundOn=!soundOn;if(!soundOn)stopCurrentAudio();e.currentTarget.classList.toggle('off',!soundOn);e.currentTarget.setAttribute('aria-pressed',soundOn);e.currentTarget.innerHTML=`<span class="sound-icon" aria-hidden="true">${soundOn?'🔊':'🔇'}</span> ${soundOn?'聲音開啟':'聲音關閉'}`;});
document.querySelector('#playAll').addEventListener('click',e=>{ if(!soundOn)return; if(sequenceTimer){clearTimeout(sequenceTimer);sequenceTimer=null;stopCurrentAudio();return} const list=groups[current].cards; let i=0; const next=()=>{if(i>=list.length){sequenceTimer=null;setPlayAllButton(false);return}speak(list[i++][0],'sequence');sequenceTimer=setTimeout(next,850)};next();});
renderTabs();renderCards();
